# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3aa05f00980bda4dfca1b3d8495e8920bcae2ff6baefcb8ba00748ee619f3e8569be29254c8cf95ac37c36a2bbabce17a3dd253370978fd99600d8962384a697

test:
  secret_key_base: 543c395ae9881057b88a2be158f0142726cd2dc995e3d96db19996b2bcafb1a9a01b5ca5da7e1f58fb0bcbbd0259683218331a12e00cd7419f7556d07dc3f2aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
